package core

import (
	"fmt"
	"time"
)

// ModelInfo holds basic info about an available model.
type ModelInfo struct {
	ID      string `json:"id"`
	OwnedBy string `json:"owned_by"`
}

// Usage tracks token consumption for a single completion.
type Usage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// FunctionDefinition describes a callable function for the model.
type FunctionDefinition struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Parameters  any    `json:"parameters,omitempty"` // json.RawMessage or a struct
	Strict      bool   `json:"strict,omitempty"`
}

// Tool represents a tool (currently only functions) that the model may call.
type Tool struct {
	Type     string              `json:"type"` // "function"
	Function *FunctionDefinition `json:"function,omitempty"`
}

// ToolChoice controls how the model uses tools.
type ToolChoice struct {
	Type     string `json:"type"` // "none" | "auto" | "required" | "function"
	Function struct {
		Name string `json:"name"`
	} `json:"function,omitempty"`
}

// FunctionCall represents a function call generated by the model.
type FunctionCall struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"` // JSON string
}

// ToolCall represents a tool call (currently function call) generated by the model.
type ToolCall struct {
	ID       string       `json:"id"`
	Type     string       `json:"type"` // "function"
	Function FunctionCall `json:"function"`
	Index    int          `json:"index,omitempty"`
}

// Message represents a single message in the chat completion request/response.
type Message struct {
	Role             string     `json:"role"`
	Content          string     `json:"content,omitempty"`
	ReasoningContent string     `json:"reasoning_content,omitempty"`
	Name             string     `json:"name,omitempty"`         // function name for tool results
	ToolCalls        []ToolCall `json:"tool_calls,omitempty"`   // assistant messages with tool calls
	ToolCallID       string     `json:"tool_call_id,omitempty"` // tool result messages
}

// ChatCompletionRequest is the unified request type for all providers.
type ChatCompletionRequest struct {
	Model             string         `json:"model"`
	Messages          []Message      `json:"messages"`
	Temperature       float32        `json:"temperature,omitempty"`
	MaxTokens         int            `json:"max_tokens,omitempty"`
	TopP              float32        `json:"top_p,omitempty"`
	PresencePenalty   float32        `json:"presence_penalty,omitempty"`
	FrequencyPenalty  float32        `json:"frequency_penalty,omitempty"`
	Stop              []string       `json:"stop,omitempty"`
	Seed              *int           `json:"seed,omitempty"`
	ResponseFormat    ResponseFormat `json:"response_format,omitempty"`
	Stream            bool           `json:"stream,omitempty"`
	Tags              []string       `json:"tags,omitempty"` // Optional tags for filtering/categorizing calls in history
	Tools             []Tool         `json:"tools,omitempty"`
	ToolChoice        any            `json:"tool_choice,omitempty"` // "none" | "auto" | "required" or ToolChoice
	ParallelToolCalls bool           `json:"parallel_tool_calls,omitempty"`

	// Metadata is an in-memory map for interceptors to pass data between
	// BeforeRequest and AfterResponse hooks. It is not serialized to JSON.
	Metadata map[string]any `json:"-"`
}

// Validate checks the request for common misconfigurations.
// Returns a slice of error messages; empty slice means valid.
func (req ChatCompletionRequest) Validate() []string {
	var issues []string
	if len(req.Messages) == 0 {
		issues = append(issues, "messages cannot be empty")
	}
	for i, m := range req.Messages {
		if m.Role == "" {
			issues = append(issues, fmt.Sprintf("message[%d]: role is required", i))
		}
		if m.Content == "" && m.Role != "assistant" && m.Role != "tool" {
			// assistant messages can be empty (e.g. tool calls), tool messages use tool_call_id
			issues = append(issues, fmt.Sprintf("message[%d]: content is required", i))
		}
	}
	if req.Temperature < 0 || req.Temperature > 2 {
		issues = append(issues, "temperature must be between 0 and 2")
	}
	if req.TopP < 0 || req.TopP > 1 {
		issues = append(issues, "top_p must be between 0 and 1")
	}
	if req.MaxTokens < 0 {
		issues = append(issues, "max_tokens must be >= 0")
	}
	return issues
}

// ResponseFormat controls the output format (e.g. JSON object).
type ResponseFormat struct {
	Type string `json:"type"`
}

// ChatCompletionResponse is the unified response type for all providers.
type ChatCompletionResponse struct {
	ID        string    `json:"id"`
	Model     string    `json:"model"`
	Choices   []Choice  `json:"choices"`
	Usage     Usage     `json:"usage"`
	CreatedAt time.Time `json:"created_at"`
}

// Content returns the content of the first choice, or empty string if none.
// This is a safe convenience accessor that avoids index-out-of-bounds panics.
func (r *ChatCompletionResponse) Content() string {
	if r == nil || len(r.Choices) == 0 {
		return ""
	}
	return r.Choices[0].Message.Content
}

// Choice represents a single completion choice.
type Choice struct {
	Index        int     `json:"index"`
	Message      Message `json:"message"`
	FinishReason string  `json:"finish_reason"`
}

// ProviderHealth represents the runtime health metrics of a provider.
type ProviderHealth struct {
	LastCheckAt      time.Time `json:"last_check_at"`
	LastLatencyMs    int64     `json:"last_latency_ms"`
	AvgLatencyMs     int64     `json:"avg_latency_ms"`
	SuccessRate      float64   `json:"success_rate"`       // 0.0~1.0, recent window
	ConsecutiveFails int       `json:"consecutive_fails"`
	TotalChecks      int       `json:"total_checks"`
}

// ProviderStatus represents the runtime status of a provider.
type ProviderStatus struct {
	Name      string         `json:"name"`
	Available bool           `json:"available"`
	Model     string         `json:"model"`
	Health    ProviderHealth `json:"health,omitempty"`
}

// StreamChunk represents a single chunk from an SSE stream.
type StreamChunk struct {
	Index        int     `json:"index"`
	Delta        Message `json:"delta"`
	FinishReason string  `json:"finish_reason,omitempty"`
}

// StreamCompletionResponse is yielded for each chunk during streaming.
type StreamCompletionResponse struct {
	ID    string      `json:"id"`
	Model string      `json:"model"`
	Chunk StreamChunk `json:"chunk"`
	// Usage is set only on the final chunk when the provider supports it
	// (e.g. OpenAI with stream_options: {"include_usage": true}).
	Usage Usage `json:"usage,omitempty"`
	// Err is set when the stream encounters a non-EOF error.
	// When Err is non-nil, the channel will be closed immediately after.
	Err error `json:"-"`
}

// DualResult holds results from dual-provider completion.
type DualResult struct {
	Result1   *ChatCompletionResponse `json:"result1"`
	Result2   *ChatCompletionResponse `json:"result2"`
	Consensus bool                    `json:"consensus"`
}

// AuditResult holds the outcome of an audit pass.
type AuditResult struct {
	Primary   *ChatCompletionResponse `json:"primary"`
	Audit     *ChatCompletionResponse `json:"audit"`
	Consensus bool                    `json:"consensus"`
	Adjusted  *ChatCompletionResponse `json:"adjusted"`
}

// Clone creates a deep copy of the request, including Messages, Tags, and Tools.
func (req ChatCompletionRequest) Clone() ChatCompletionRequest {
	cloned := req
	if len(req.Messages) > 0 {
		cloned.Messages = make([]Message, len(req.Messages))
		for i, m := range req.Messages {
			cloned.Messages[i] = m
			if len(m.ToolCalls) > 0 {
				cloned.Messages[i].ToolCalls = make([]ToolCall, len(m.ToolCalls))
				copy(cloned.Messages[i].ToolCalls, m.ToolCalls)
			}
		}
	}
	if len(req.Tags) > 0 {
		cloned.Tags = make([]string, len(req.Tags))
		copy(cloned.Tags, req.Tags)
	}
	if len(req.Tools) > 0 {
		cloned.Tools = make([]Tool, len(req.Tools))
		copy(cloned.Tools, req.Tools)
	}
	if len(req.Metadata) > 0 {
		cloned.Metadata = make(map[string]any, len(req.Metadata))
		for k, v := range req.Metadata {
			cloned.Metadata[k] = v
		}
	}
	return cloned
}
